#!/bin/bash
set -euo pipefail

# Everything created here holds secrets (VPN passwords, admin hash).
umask 077

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log()  { echo -e "${GREEN}[+]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
err()  { echo -e "${RED}[✗]${NC} $1"; exit 1; }

if [ "$(id -u)" -ne 0 ]; then err "Run as root"; fi

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║  TrustTunnel Client + Panel Installer    ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════╝${NC}"
echo ""

# trusttunnel_client lives in its OWN repository, separate from the endpoint.
CLIENT_VERSION="${CLIENT_VERSION:-1.1.5}"
CLIENT_REPO="https://github.com/TrustTunnel/TrustTunnelClient"
TT_GPG_KEY="${TT_GPG_KEY:-28645AC9776EC4C00BCE2AFC0FE641E7235E2EC6}"

CLIENT_DIR="${TT_CLIENT_DIR:-/opt/trusttunnel_client}"
CONFIG_DIR="${TT_CONFIG_DIR:-/etc/trusttunnel}"
PANEL_DIR="${TT_CLIENT_PANEL_DIR:-/opt/tt-client-panel}"
PANEL_REPO="${PANEL_REPO:-https://github.com/maksym8787/tt-panel.git}"
SERVICE_NAME="trusttunnel-client"
PANEL_SERVICE="tt-client-panel"

GATEWAY_IF="${TT_GATEWAY_IF:-eth0}"
TUN_IF="${TT_TUN_IF:-tun0}"
LAN_GATEWAY="${TT_LAN_GATEWAY:-10.10.9.1}"
LAN_NETWORK="${TT_LAN_NETWORK:-10.10.0.0/16}"
PANEL_PORT="${TT_CLIENT_PANEL_PORT:-8443}"
PANEL_HOST="${TT_CLIENT_PANEL_HOST:-127.0.0.1}"

case "$(uname -m)" in
    x86_64|amd64) ARCH="x86_64" ;;
    aarch64|arm64) ARCH="aarch64" ;;
    armv7l) ARCH="armv7" ;;
    *) err "Unsupported architecture: $(uname -m)" ;;
esac

log "Installing dependencies..."
export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_SUSPEND=1
apt update
apt install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
    python3 python3-venv python3-pip git curl gnupg iproute2 iputils-ping

log "Creating directories..."
mkdir -p "$CLIENT_DIR" "$CONFIG_DIR/configs" "$PANEL_DIR"
chmod 755 "$CLIENT_DIR"
chmod 700 "$CONFIG_DIR/configs"
chmod 755 "$CONFIG_DIR"
chmod 700 "$PANEL_DIR"

if [ ! -f "$CLIENT_DIR/trusttunnel_client" ]; then
    PKG="trusttunnel_client-v${CLIENT_VERSION}-linux-${ARCH}.tar.gz"
    URL="${CLIENT_REPO}/releases/download/v${CLIENT_VERSION}/${PKG}"
    log "Downloading trusttunnel_client v${CLIENT_VERSION} (${ARCH})..."
    curl -fSL "$URL" -o /tmp/tt-client.tar.gz || err "Download failed: $URL"

    EXTRACT="$(mktemp -d)"
    tar -xzf /tmp/tt-client.tar.gz -C "$EXTRACT"
    rm -f /tmp/tt-client.tar.gz

    BIN_SRC="$(find "$EXTRACT" -name trusttunnel_client -type f | head -n1)"
    [ -z "$BIN_SRC" ] && err "trusttunnel_client not found inside the archive"

    # Verify before it ever runs as root. Skip with TT_SKIP_GPG=1.
    if [ "${TT_SKIP_GPG:-0}" != "1" ] && [ -f "${BIN_SRC}.sig" ]; then
        if ! gpg --list-keys "$TT_GPG_KEY" >/dev/null 2>&1; then
            gpg --keyserver keys.openpgp.org --recv-key "$TT_GPG_KEY" >/dev/null 2>&1 \
                || warn "Could not fetch the AdGuard signing key"
        fi
        if gpg --verify "${BIN_SRC}.sig" "$BIN_SRC" >/dev/null 2>&1; then
            log "GPG signature verified (AdGuard)"
        else
            rm -rf "$EXTRACT"
            err "GPG verification FAILED — refusing to install. Override with TT_SKIP_GPG=1."
        fi
    else
        warn "No signature next to the binary — installing unverified."
    fi

    mv "$BIN_SRC" "$CLIENT_DIR/trusttunnel_client"
    SW="$(find "$EXTRACT" -name setup_wizard -type f | head -n1)"
    [ -n "$SW" ] && mv "$SW" "$CLIENT_DIR/setup_wizard" && chmod +x "$CLIENT_DIR/setup_wizard"
    rm -rf "$EXTRACT"
    chmod +x "$CLIENT_DIR/trusttunnel_client"
    log "trusttunnel_client installed"
else
    log "trusttunnel_client already present, skipping download"
fi

log "Creating routes helper..."
cat > "$CLIENT_DIR/setup-routes.sh" << ROUTEEOF
#!/bin/bash
# Regenerated by the panel whenever the active server changes.
sleep 5
ip route del default via ${LAN_GATEWAY} 2>/dev/null
ip route add default dev ${TUN_IF} 2>/dev/null
ip route add ${LAN_NETWORK} via ${LAN_GATEWAY} dev ${GATEWAY_IF} 2>/dev/null
exit 0
ROUTEEOF
chmod 755 "$CLIENT_DIR/setup-routes.sh"

log "Creating $SERVICE_NAME service..."
cat > "/etc/systemd/system/${SERVICE_NAME}.service" << EOF
[Unit]
Description=TrustTunnel VPN client
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$CONFIG_DIR
# The client takes its config via -c/--config; there is no positional argument.
ExecStart=$CLIENT_DIR/trusttunnel_client -c $CONFIG_DIR/active-config.toml
ExecStartPost=$CLIENT_DIR/setup-routes.sh
# Since client v1.1.5 the process exits after its recovery attempts are
# exhausted (~1 min), so it must be restarted; the panel fails over separately.
Restart=always
RestartSec=5
LimitNOFILE=65535

NoNewPrivileges=true
ProtectHome=true
ProtectSystem=strict
ReadWritePaths=$CONFIG_DIR $CLIENT_DIR
PrivateTmp=true
ProtectKernelModules=true
ProtectControlGroups=true
RestrictSUIDSGID=true
RestrictRealtime=true
LockPersonality=true
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_RAW CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_RAW

[Install]
WantedBy=multi-user.target
EOF

log "Installing the panel..."
cd /tmp
rm -rf tt-client-install
if [ -n "${PANEL_REF:-}" ]; then
    git clone --depth 1 --branch "$PANEL_REF" "$PANEL_REPO" tt-client-install || err "Clone failed"
else
    git clone --depth 1 "$PANEL_REPO" tt-client-install || err "Clone failed"
fi
[ -d tt-client-install/tt-client-panel ] || err "tt-client-panel/ missing in the repository"

for f in auth.py config.py health.py main.py routes.py servers.py; do
    cp "tt-client-install/tt-client-panel/$f" "$PANEL_DIR/"
done
cp -r tt-client-install/tt-client-panel/frontend "$PANEL_DIR/"
cp -r tt-client-install/tt-client-panel/static "$PANEL_DIR/"
rm -rf /tmp/tt-client-install
find "$PANEL_DIR" -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true

if [ ! -d "$PANEL_DIR/venv" ]; then
    log "Creating Python venv..."
    python3 -m venv "$PANEL_DIR/venv"
fi
"$PANEL_DIR/venv/bin/pip" install --quiet --upgrade pip
"$PANEL_DIR/venv/bin/pip" install --quiet fastapi uvicorn

log "Creating $PANEL_SERVICE service..."
cat > "/etc/systemd/system/${PANEL_SERVICE}.service" << EOF
[Unit]
Description=TrustTunnel Client Panel
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$PANEL_DIR
ExecStart=$PANEL_DIR/venv/bin/python3 main.py
Restart=always
RestartSec=3
Environment=PYTHONUNBUFFERED=1
Environment=TT_CLIENT_DIR=$CLIENT_DIR
Environment=TT_CONFIG_DIR=$CONFIG_DIR
Environment=TT_CLIENT_PANEL_DIR=$PANEL_DIR
Environment=TT_CLIENT_PANEL_PORT=$PANEL_PORT
Environment=TT_CLIENT_PANEL_HOST=$PANEL_HOST
Environment=TT_GATEWAY_IF=$GATEWAY_IF
Environment=TT_TUN_IF=$TUN_IF
Environment=TT_LAN_GATEWAY=$LAN_GATEWAY
Environment=TT_LAN_NETWORK=$LAN_NETWORK
# Uncomment when behind a TLS-terminating reverse proxy:
# Environment=TT_BEHIND_PROXY=1

ProtectHome=true
ProtectSystem=full
ReadWritePaths=$PANEL_DIR $CONFIG_DIR $CLIENT_DIR
PrivateTmp=true
ProtectKernelTunables=true
ProtectKernelModules=true
RestrictSUIDSGID=true
RestrictRealtime=true
LockPersonality=true

[Install]
WantedBy=multi-user.target
EOF

log "Creating deploy script..."
cat > "$PANEL_DIR/deploy.sh" << DEPLOYEOF
#!/bin/bash
set -euo pipefail
umask 077
cd /tmp
rm -rf tt-client-deploy
git clone --depth 1 ${PANEL_REPO} tt-client-deploy \\
    || { echo "Clone failed, keeping the current deployment" >&2; exit 1; }
for f in auth.py config.py health.py main.py routes.py servers.py; do
    cp "tt-client-deploy/tt-client-panel/\$f" ${PANEL_DIR}/
done
cp -r tt-client-deploy/tt-client-panel/frontend ${PANEL_DIR}/
cp -r tt-client-deploy/tt-client-panel/static ${PANEL_DIR}/
rm -rf /tmp/tt-client-deploy
find ${PANEL_DIR} -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
chmod 700 ${PANEL_DIR}
chmod 600 ${PANEL_DIR}/panel.json 2>/dev/null || true
systemctl restart ${PANEL_SERVICE}
echo "Deployed at \$(date)"
DEPLOYEOF
chmod 755 "$PANEL_DIR/deploy.sh"

log "Enabling services..."
systemctl daemon-reload
systemctl enable "$PANEL_SERVICE" >/dev/null 2>&1
# The VPN client is enabled but NOT started: it has no active config until a
# server is added through the panel.
systemctl enable "$SERVICE_NAME" >/dev/null 2>&1
systemctl restart "$PANEL_SERVICE"

log "Waiting for the panel..."
for _ in $(seq 1 30); do
    if curl -sk "http://127.0.0.1:${PANEL_PORT}/api/auth-status" >/dev/null 2>&1; then break; fi
    sleep 1
done

echo ""
echo -e "${GREEN}════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Client panel installed${NC}"
echo -e "${GREEN}════════════════════════════════════════════${NC}"
echo ""
echo -e "  Client:  ${CYAN}$(${CLIENT_DIR}/trusttunnel_client --version 2>/dev/null || echo v${CLIENT_VERSION})${NC}"
echo -e "  Panel:   ${CYAN}http://${PANEL_HOST}:${PANEL_PORT}${NC}"
echo -e "  Status:  $(systemctl is-active ${PANEL_SERVICE} 2>/dev/null)"
echo ""
if [ "$PANEL_HOST" = "127.0.0.1" ]; then
    echo -e "  ${YELLOW}The panel listens on loopback only (no TLS).${NC}"
    echo -e "  Reach it with: ${CYAN}ssh -L ${PANEL_PORT}:127.0.0.1:${PANEL_PORT} root@<this-host>${NC}"
    echo -e "  To expose it, put a TLS proxy in front and set TT_BEHIND_PROXY=1."
fi
echo ""
echo -e "  ${YELLOW}1. Open the panel and create the admin password (min 12 chars)${NC}"
echo -e "  ${YELLOW}2. Add a server (paste a tt:// deeplink) — it starts the VPN${NC}"
echo ""
echo -e "  Deploy updates:  ${CYAN}${PANEL_DIR}/deploy.sh${NC}"
echo ""
